### ISSUE TITLE
Nested Archetypes

### ISSUE THREAD

**Issue by LoganLehman** [leekelleher/umbraco-ditto-labs#6]
@leekelleher,

Does the DittoArchetype/DittoDocTypeFactory combination works for nested Archetypes? I have this class:

```
    public class Menu
    {
        [DittoArchetype]
        [DittoDocTypeFactory]
        public IEnumerable<IMenuItem> MenuItems { get; set; }
    }
```

This collection is a collection of this class:

```
    public class MenuItem : IMenuItem
    {

    public string Label { get; set; }

    [DittoArchetype]
    [LinkProcessor]
    public ILink Link { get; set; }

    [DittoArchetype]
    [DittoDocTypeFactory]
    public IEnumerable<IMenuItem> Children { get; set; }


    }
```

The first level of the menu items within the `Menu` class works great, but nested `Children` does not map at all apparently. I may not be using the correct methodology for this. 

I have tried this without using interfaces as well, so I don't think it has to do with the Factory stuff. You can see my Archetype here:

![menuitem](https://cloud.githubusercontent.com/assets/1081678/17119765/cb7de88a-527c-11e6-8ff1-a7bf5e04af4f.png)

**Comment by Nicholas-Westby** [comment]
For what it's worth, Ditto maps nested Archetypes just fine for me. Here's an example of what my content looks like (multiple "Content + Sidebar" widgets are nested):

![nested](https://cloud.githubusercontent.com/assets/5933222/17120055/a9e2cd56-527e-11e6-9f10-be57dcfb56c7.png)

Ditto maps it and it is rendered on the page exactly as I'd expect it to. Here's what my `ContentWithSidebar` class looks like:

``` cs
namespace MyProject
{

    // Namespaces.
    using Common;
    using Mapping.Interfaces;
    using Newtonsoft.Json;
    using Processors;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Utility;

    /// <summary>
    /// Content widgets and sidebar widgets.
    /// </summary>
    public class ContentWithSidebar : Widget
    {

        #region Properties

        /// <summary>
        /// The main content widgets.
        /// </summary>
        [JsonIgnore]
        [DittoMixedArchetype]
        public IEnumerable<IWidget> MainContent { get; set; }

        /// <summary>
        /// The sidebar content widgets.
        /// </summary>
        [JsonIgnore]
        [DittoMixedArchetype]
        public IEnumerable<IWidget> Sidebar { get; set; }

        #endregion

        #region Overridden Methods

        /// <summary>
        /// Renders the content with sidebar widget and all of the widgets inside of it.
        /// </summary>
        /// <param name="helper">
        /// The HTML helper.
        /// </param>
        /// <returns>
        /// The rendered Angular directive.
        /// </returns>
        public override string Render(HtmlHelper helper)
        {
            var contentItems = MainContent.Select(x => x.Render(helper));
            var sidebarItems = Sidebar.Select(x => x.Render(helper));
            var combinedContent = string.Join(Environment.NewLine, contentItems);
            var combinedSidebar = string.Join(Environment.NewLine, sidebarItems);
            var innerMarkup = $@"
                <div content=""main"">
                    {combinedContent}
                </div>
                <div content=""sidebar"">
                    {combinedSidebar}
                </div>";
            return WidgetUtility.ConvertWidgetToDirective(this, helper, innerMarkup);
        }

        /// <summary>
        /// Gets the JSON representation of the data for this widget.
        /// </summary>
        /// <returns>
        /// Null.
        /// </returns>
        /// <remarks>
        /// Since this widget has no data, null is returned.
        /// </remarks>
        public override string ToJson()
        {
            return null;
        }

        #endregion

    }

}
```

There's some non-Ditto stuff in there, but you get the idea. My DittoMixedArchetype processor is just a multi-processor that combines the same two you are using:

``` cs
namespace MyProject.Processors
{

    // Namespaces.
    using Our.Umbraco.Ditto;
    using System.Collections.Generic;

    /// <summary>
    /// This multi-processor combines the Archetype and DocTypeFactory processors to allow for
    /// both of those processors to be run with this single unified processor rather than
    /// having to specify the other two.
    /// </summary>
    /// <remarks>
    /// This can be used when you have an Umbraco property that is an Archetype that allows for
    /// multiple items and multiple fieldset types (e.g., a widget collection).
    /// </remarks>
    public class DittoMixedArchetypeAttribute : DittoMultiProcessorAttribute
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public DittoMixedArchetypeAttribute() : base(GetProcessors())
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns the processors that should be run whenever this multi-processor is used.
        /// </summary>
        /// <returns>
        /// The collection of processors to run.
        /// </returns>
        private static IEnumerable<DittoProcessorAttribute> GetProcessors()
        {
            return new DittoProcessorAttribute[]
            {
                // First, the Archetype processor converts the ArchetypeModel
                // to an IPublishedContent collection.
                new DittoArchetypeAttribute(),
                // Next, the DocType processor converts each item in the previously
                // created collection to a type that is indicated by the alias of the
                // item (since they were created from Archetypes, this alias corresponds
                // to the fieldset alias for each item).
                new DittoDocTypeFactoryAttribute()
            };
        }

        #endregion

    }

}
```

I am using Ditto 0.10.0-alpha-000586 from this MyGet feed: https://www.myget.org/gallery/umbraco-ditto

Note that there is a newer one. Might be useful to post which version you are using.

**Comment by LoganLehman** [comment]
@Nicholas-Westby,

Thanks for the input as always! Miss working with you.

Anyhow, I was using .00058**0** - I have updated and now it is at  .00058**7** and still doesn't seem to be working. 

Hmm... I republished the entire site and removed TEMP just be sure.

**Comment by Nicholas-Westby** [comment]
I wonder if you're running into the same Ditto bug (or feature, depending on your perspective) I ran into: https://github.com/leekelleher/umbraco-ditto/issues/181

That is, "Item" is a property that exists on `IPublishedContent` and so that confuses Ditto. In your case, perhaps "Children" is a property that also exists on `IPublishedContent`. In the case of an `ArchetypePublishedContent` (which implements `IPublishedContent`), I imagine that would be an empty collection.

Maybe if you rename it to something like "ChildItems" it will start working. You'd have to do that in the very least on your Archetype data and possibly also for your classes/interfaces.

**Comment by LoganLehman** [comment]
@Nicholas-Westby,

I just tried your suggestion, and you were correct! Thank you so much. 

I guess this can be closed. Hopefully they can find a way to fix the `IPublishedContent` stuff

**Comment by leekelleher** [comment]
@Nicholas-Westby Would it be helpful to include your `DittoMixedArchetypeAttribute` processor in the Ditto Labs repo?

**Comment by Nicholas-Westby** [comment]
You could if you like. It wouldn't help me specifically, as I don't use Ditto Labs (I just use it as a reference for code that I include separately in my projects).

**Comment by leekelleher** [comment]
@Nicholas-Westby I'm not using Ditto Labs assemblies directly in my projects either, so far it's purely a "show & tell" repository. To hopefully let others learn from it, etc.

Is the code snippet in the [above comment](#issuecomment-235111089) your latest & greatest?

**Comment by Nicholas-Westby** [comment]
Sure is.

**Comment by leekelleher** [comment]
@Nicholas-Westby Cool, thanks.
