### ISSUE TITLE
`ChildrenAs` processor

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto-labs#7]
Add a processor that will take the current content node's and return its children nodes. Filterable by doctype alias.

**Comment by mattbrailsford** [comment]
Hmmm, the simplicity of ChildrenAs sounds nice, but wondering if we shouldn't have a Filter attribute and just chain it with UmbracoPropperty("Children")?

**Comment by leekelleher** [comment]
Good suggestion, as then a Filter processor can be use against other collections of nodes (e.g. from pickers).  Then could make ChildrenAs with a multi-processor wrapper.

**Comment by mattbrailsford** [comment]
Yup. I'm guessing the filter attribute will have to point to a type though
as can't do dynamic stuff in attributes, in which case you wonder, is there
a point? Or should it just be documented as a pattern?

**Comment by mattbrailsford** [comment]
But dynamic stuff in attributes I mean at the [attribute] declaration
point.

**Comment by leekelleher** [comment]
I've been playing around with some code... so far, I've ended up creating an abstract class called `PublishedContentFilter`, that has a property of type `Func<IPublishedContent, bool>`.

We'll see how it pans out, _just experimenting at the moment_

**Comment by leekelleher** [comment]
Closing this ticket; opened PR #8 - we can discuss further on there
